#!/bin/sh -e
cd "$(dirname "$0")"

copy()
{
	printf "%-25s %s\n" "$1" "$2/$(basename $1)"
	cp -r "$1" "$2"
}

shared()
{
	copy dots/.config/emacs       $HOME/.config
	copy dots/.config/git         $HOME/.config
	copy dots/.config/lf          $HOME/.config
	copy dots/.config/mpd         $HOME/.config
	copy dots/.config/ncmpcpp     $HOME/.config
	copy dots/.config/notmuch     $HOME/.config
	copy dots/.config/offlineimap $HOME/.config
	copy dots/.config/zsh         $HOME/.config
	copy dots/.config/aliasrc     $HOME/.config
	copy dots/.local/bin          $HOME/.local
	copy dots/.local/share/emacs  $HOME/.local/share
	copy dots/.local/share/gnupg  $HOME/.local/share
}

case $1 in
	linux)
		shared
		copy dots/.config/compton        $HOME/.config
		copy dots/.config/dunst          $HOME/.config
		copy dots/.config/vis            $HOME/.config
		copy dots/.config/mimeapps.list  $HOME/.config
		copy dots/.xinitrc               $HOME
		copy dots/.xprofile              $HOME
		copy dots/.zprofile              $HOME
		;;
	macos)
    		shared
    		copy dots/.config/alacritty  $HOME/.config
    		copy dots/.zshenv            $HOME
		;;
	*)
		echo "Usage: $0 [linux|macos]"
		exit 2
		;;
esac
