#!/bin/sh -e

rice_dir=$HOME/.config/rice

copy()
{
	printf "%-25s %s\n" "$1" "$2/$(basename $1)"
	cp -r "$1" "$2"
}

shared()
{
	# Dotfiles used on all operating systems
	copy dots/.config/emacs       $HOME/.config
	copy dots/.config/git         $HOME/.config
	copy dots/.config/lf          $HOME/.config
	copy dots/.config/mpd         $HOME/.config
	copy dots/.config/ncmpcpp     $HOME/.config
	copy dots/.config/notmuch     $HOME/.config
	copy dots/.config/offlineimap $HOME/.config
	copy dots/.config/zsh         $HOME/.config
	copy dots/.config/aliasrc     $HOME/.config
	copy dots/.local/bin          $HOME/.local
	copy dots/.local/share/emacs  $HOME/.local/share
	copy dots/.local/share/gnupg  $HOME/.local/share
}

linux()
{
	# Linux specific dotfiles
	copy dots/.config/compton        $HOME/.config
	copy dots/.config/dunst          $HOME/.config
	copy dots/.config/vis            $HOME/.config
	copy dots/.config/mimeapps.list  $HOME/.config
	copy dots/.xinitrc               $HOME
	copy dots/.xprofile              $HOME
	copy dots/.zprofile              $HOME
}

macos()
{
	# macOS specific dotfiles
	copy dots/.config/alacritty  $HOME/.config
	copy dots/.zshenv            $HOME
}

if [ -d "$rice_dir" ]; then
	cd "$rice_dir"
	git pull --ff-only
else
	mkdir -p ~/.config
	git clone https://github.com/mjfeller/rice "$rice_dir"
fi

if [ ! -d ~/.ssh ]; then
	mkdir ~/.ssh
fi

cd "$rice_dir"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	shared; linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
	shared; macos
else
	echo "Usage: $0"; exit 2
fi
