#!/bin/sh

user=mjf
logfile=log
progsfile=packages.csv

error() { printf "Error: %s\\n" "$1" | tee -a $logfile; exit; }
log()   { printf "$1\\n" | tee -a $logfile; }

install() { 
	log "Insatlling '$1' ($n of $total). $1 $2"
	dnf install -y $1 >> $logfile
}

installation_loop() {
	log "Beginning package installation installation"
	cat $progsfile | sed '/^#/d' | sed '/^$/d' > /tmp/progs.csv
	total=$(wc -l < /tmp/progs.csv)
	while IFS=, read -r program comment; do
		n=$((n+1))
		echo "$comment" | grep "^\".*\"$" >/dev/null 2>&1 && comment="$(echo "$comment" | sed "s/\(^\"\|\"$\)//g")"
		install "$program" "$comment"
	done < /tmp/progs.csv
}

install_dots() {
	log "Stowing dot files"
	(cd .. && su -c ./install $user)
}

# create or truncate logfile
> $logfile

# check for root
if [[ $EUID -ne 0 ]]; then error "This script must be run as root"; fi

installation_loop
install_dots
log "Installation complete"
