#!/bin/sh

# alias ls="ls -F --group-directories-first"
alias ls="ls -F"
alias l="ls -lAh"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias q="exit"
alias vi=vim

alias weather="curl wttr.in/\~Boulder+Colorado"

# Youtube
alias yt="youtube-dl"
alias yta='youtube-dl --extract-audio --audio-quality 0 --audio-format flac --output "%(title)s.%(ext)s"'
alias ytad='youtube-dl --extract-audio --audio-quality 0 --audio-format flac --output "%(title)s [%(upload_date)s].%(ext)s"'

alias fp='pash c $(pash l | fzf)'
