#!/bin/sh
cd "$(dirname "$0")" || exit 1
set -e

pkgfile=${pkgfile:-"https://gitlab.com/mark.feller/rice/raw/master/pkgs/fedora/packages"}
tmpfile=/tmp/pkgs

log() {
    printf '\033[1;33m%s \033[m%s\033[m %s\n' \
           "${3:-->}" "${2:+[1;36m}$1${2:+[m}" "$2"
}

# Copy a real file to our temp progsfile or attempt to curl the progsfile
([ -f "$pkgfile" ] && cp "$pkgfile" "$tmpfile") || curl -Ls "$pkgfile" > "$tmpfile"

packages=$(sed '/^$/d' /tmp/progs | sed '/^#/d')
while IFS='	' read -r program comment; do
    log "Installing $program $comment"
    dnf install -y $program
done <<EOF
$packages
EOF
