#!/bin/sh

progsfile={$progsfile:-"https://raw.githubusercontent.com/LukeSmithxyz/LARBS/master/progs.csv"}

log() {
    # Print a message prettily.
    #
    # This function uses the literal escape character (Ctrl+V+Escape) as
    # a simple way of *safely* bypassing the escape sequence restrictions
    # on 'printf %s'. Cheeky, I know.
    #
    # '\033[1;32m'      Set text to color '2' and make it bold.
    # '\033[m':         Reset text formatting.
    # '${3:-->}':       If the 3rd argument is missing, set prefix to '->'.
    # '${2:+[1;3Xm}':   If the 2nd argument exists, set the text style of '$1'.
    # '$((${#1}%5+1))': Color the package name based on its length.
    # '${2:+[m}':       If the 2nd argument exists, reset text formatting.
    printf '\033[1;33m%s \033[m%s\033[m %s\n' \
           "${3:-->}" "${2:+[1;36m}$1${2:+[m}" "$2"
}

die() {
    # Print a message and exit with '1' (error).
    log "$1" "$2" "!>" >&2
    exit 1
}

([ -f "$progsfile" ] && cp "$progsfile" /tmp/progs.csv) || curl -Ls "$progsfile" | sed '/^#/d' | eval grep "$grepseq" > /tmp/progs.csv

packages=$(sed '/^$/d' packages.csv | sed '/^#/d')
while IFS='	' read -r program comment; do
    log "Installing $program $comment"
    dnf install -y $program
done <<EOF
$packages
EOF
