#!/bin/sh
set -e

pkgfile=${pkgfile:-"https://gitlab.com/mark.feller/rice/raw/master/pkgs/fedora/packages"}

log() {
    printf '\033[1;33m%s \033[m%s\033[m %s\n' \
           "${3:-->}" "${2:+[1;36m}$1${2:+[m}" "$2"
}

# Copy a real file to our temp progsfile or attempt to curl the progsfile
([ -f "$pkgfile" ] && cp "$pkgfile" /tmp/pkgs) || curl -Ls "$pkgfile" > /tmp/pkgs

packages=$(sed '/^$/d' /tmp/pkgs | sed '/^#/d')
while IFS=' ' read -r program comment; do
    log "Installing $program $comment"
    dnf install -y $program
done <<EOF
$packages
EOF
