#!/bin/sh
set -e

dotsrepo=${dotfilesrepo:-"https://gitlab.com/mark.feller/rice.git"}
pkgfile=${pkgfile:-"https://gitlab.com/mark.feller/rice/raw/master/pkgs/macos/packages"}

trim_string() {
    # Usage: trim_string "   example   string    "
    trim=${1#${1%%[![:space:]]*}}
    trim=${trim%${trim##*[![:space:]]}}
    printf '%s\n' "$trim"
}

log() {
    printf '\033[1;33m%s \033[m%s\033[m %s\n' \
           "->" "${2:+[1;36m}$1${2:+[m}" "$2"
}

install_packages() {
    # Copy a real file to our temp pkgfile or attempt to curl the pkgfile
    ([ -f "$pkgfile" ] && cp "$pkgfile" /tmp/pkgs) || curl -Ls "$pkgfile" > /tmp/pkgs

    packages=$(sed '/^$/d' /tmp/pkgs | sed '/^#/d')
    while IFS='	' read -r flag program comment; do
        program=$(trim_string $program)
        case $flag in
            C)
                log "Installing $program cask"
                brew cask install $program || brew cask upgrade $program
                ;;
            *)
                log "Installing $program"
                brew install $program || brew upgrade $program
                ;;
        esac
    done <<EOF
$packages
EOF
}

install_dots() {
    git clone "$dotsrepo" ~/.config/rice || log "Dots have already been clone"
    (cd ~/.config/rice && ./install)
}

install_packages
install_dots
