#!/bin/sh
set -e

dotsrepo=${dotfilesrepo:-"https://gitlab.com/mark.feller/rice.git"}
pkgfile=${pkgfile:-"https://gitlab.com/mark.feller/rice/raw/master/pkgs/macos/packages"}

log() {
    printf '\033[1;33m%s \033[m%s\033[m %s\n' \
           "->" "${2:+[1;36m}$1${2:+[m}" "$2"
}

install_packages() {
    # Copy a real file to our temp progsfile or attempt to curl the progsfile
    ([ -f "$pkgfile" ] && cp "$pkgfile" /tmp/pkgs) || curl -Ls "$pkgfile" > /tmp/pkgs

    packages=$(sed '/^$/d' /tmp/pkgs | sed '/^#/d')
    while IFS=' ' read -r program comment; do
        brew install $program || brew upgrade $program
    done <<EOF
$packages
EOF
}

install_dots() {
    git clone "$dotsrepo" ~/.config/rice
    (cd ~/.config/rice && ./install)
}

post_install() {
    (cd ~/.config/rice && patch)
}

install_packages
install_dots
